import type { ResumeData, TemplateConfig } from "./types"

export const templates: TemplateConfig[] = [
  {
    id: "modern-swe",
    name: "Modern Software Engineer",
    description: "Clean, modern layout optimized for tech roles with a sidebar for skills and education.",
    category: "Technology",
    hasPhoto: false,
    fontFamily: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: { name: 28, heading: 16, subheading: 13, body: 11, small: 10 },
    spacing: { sectionGap: 16, itemGap: 10, lineHeight: 1.5 },
    colors: {
      primary: "#0f172a",
      secondary: "#334155",
      accent: "#2563eb",
      text: "#1e293b",
      background: "#ffffff",
      heading: "#0f172a",
      border: "#e2e8f0",
    },
    layout: {
      columns: 2,
      sidebarPosition: "left",
      sidebarSections: ["skills", "education", "certifications"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "clean-minimal",
    name: "Clean Minimal",
    description: "Simple single-column layout focused on readability and clarity.",
    category: "General",
    hasPhoto: false,
    fontFamily: "'Georgia', serif",
    headingFont: "'Georgia', serif",
    fontSize: { name: 26, heading: 15, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 14, itemGap: 8, lineHeight: 1.5 },
    colors: {
      primary: "#111827",
      secondary: "#4b5563",
      accent: "#111827",
      text: "#374151",
      background: "#ffffff",
      heading: "#111827",
      border: "#d1d5db",
    },
    layout: { columns: 1 },
    sectionOrder: ["header", "summary", "experience", "education", "projects", "skills", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "data-ai",
    name: "Data / AI Engineer",
    description: "Structured two-column layout emphasizing technical skills and projects.",
    category: "Technology",
    hasPhoto: false,
    fontFamily: "'Roboto Mono', monospace",
    headingFont: "'Inter', sans-serif",
    fontSize: { name: 26, heading: 15, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 14, itemGap: 8, lineHeight: 1.45 },
    colors: {
      primary: "#0c4a6e",
      secondary: "#475569",
      accent: "#0891b2",
      text: "#1e293b",
      background: "#ffffff",
      heading: "#0c4a6e",
      border: "#cbd5e1",
    },
    layout: {
      columns: 2,
      sidebarPosition: "right",
      sidebarSections: ["skills", "certifications", "education"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "projects", "experience", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "creative",
    name: "Creative",
    description: "Bold and expressive layout with accent colors and creative typography.",
    category: "Design",
    hasPhoto: false,
    fontFamily: "'Lato', sans-serif",
    headingFont: "'Playfair Display', serif",
    fontSize: { name: 30, heading: 16, subheading: 13, body: 11, small: 10 },
    spacing: { sectionGap: 18, itemGap: 10, lineHeight: 1.55 },
    colors: {
      primary: "#7c2d12",
      secondary: "#44403c",
      accent: "#ea580c",
      text: "#292524",
      background: "#ffffff",
      heading: "#7c2d12",
      border: "#d6d3d1",
    },
    layout: { columns: 1 },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "corporate",
    name: "Professional Corporate",
    description: "Formal two-column layout suited for corporate and enterprise roles.",
    category: "Business",
    hasPhoto: false,
    fontFamily: "'Times New Roman', serif",
    headingFont: "'Times New Roman', serif",
    fontSize: { name: 24, heading: 14, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 12, itemGap: 8, lineHeight: 1.4 },
    colors: {
      primary: "#1e3a5f",
      secondary: "#4a5568",
      accent: "#1e3a5f",
      text: "#2d3748",
      background: "#ffffff",
      heading: "#1e3a5f",
      border: "#cbd5e0",
    },
    layout: {
      columns: 2,
      sidebarPosition: "left",
      sidebarSections: ["education", "certifications", "skills"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "experience", "education", "skills", "certifications", "projects", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "fresher",
    name: "Fresher / Student",
    description: "Education-first layout perfect for new graduates and students.",
    category: "Entry Level",
    hasPhoto: false,
    fontFamily: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: { name: 26, heading: 15, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 14, itemGap: 8, lineHeight: 1.5 },
    colors: {
      primary: "#065f46",
      secondary: "#4b5563",
      accent: "#059669",
      text: "#1f2937",
      background: "#ffffff",
      heading: "#065f46",
      border: "#d1d5db",
    },
    layout: { columns: 1 },
    sectionOrder: ["header", "summary", "education", "projects", "skills", "experience", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: false, custom: true,
    },
  },
  // ======= Photo Templates =======
  {
    id: "photo-executive",
    name: "Executive Photo",
    description: "Premium two-column layout with a professional photo on the left sidebar. Perfect for senior roles.",
    category: "Business",
    hasPhoto: true,
    photoPosition: "left",
    fontFamily: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: { name: 26, heading: 15, subheading: 13, body: 11, small: 10 },
    spacing: { sectionGap: 14, itemGap: 8, lineHeight: 1.5 },
    colors: {
      primary: "#1e293b",
      secondary: "#475569",
      accent: "#0f766e",
      text: "#1e293b",
      background: "#ffffff",
      heading: "#0f766e",
      border: "#d1d5db",
    },
    layout: {
      columns: 2,
      sidebarPosition: "left",
      sidebarSections: ["skills", "education", "certifications"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "photo-modern-sidebar",
    name: "Modern Photo Sidebar",
    description: "Sleek dark sidebar with photo and contact details. Ideal for tech and creative roles.",
    category: "Technology",
    hasPhoto: true,
    photoPosition: "left",
    fontFamily: "'Inter', sans-serif",
    headingFont: "'Inter', sans-serif",
    fontSize: { name: 24, heading: 14, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 12, itemGap: 8, lineHeight: 1.45 },
    colors: {
      primary: "#0f172a",
      secondary: "#64748b",
      accent: "#3b82f6",
      text: "#1e293b",
      background: "#ffffff",
      heading: "#0f172a",
      border: "#e2e8f0",
    },
    layout: {
      columns: 2,
      sidebarPosition: "left",
      sidebarSections: ["skills", "education", "certifications"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "photo-creative-header",
    name: "Creative Photo Header",
    description: "Eye-catching centered photo header with a bold color banner. Great for design and marketing.",
    category: "Design",
    hasPhoto: true,
    photoPosition: "center",
    fontFamily: "'Lato', sans-serif",
    headingFont: "'Playfair Display', serif",
    fontSize: { name: 28, heading: 15, subheading: 13, body: 11, small: 10 },
    spacing: { sectionGap: 16, itemGap: 10, lineHeight: 1.55 },
    colors: {
      primary: "#6d28d9",
      secondary: "#6b7280",
      accent: "#8b5cf6",
      text: "#1f2937",
      background: "#ffffff",
      heading: "#6d28d9",
      border: "#e5e7eb",
    },
    layout: { columns: 1 },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
  {
    id: "photo-elegant-right",
    name: "Elegant Right Photo",
    description: "Classic right-aligned photo with elegant serif typography. Ideal for consulting and finance.",
    category: "Business",
    hasPhoto: true,
    photoPosition: "right",
    fontFamily: "'Georgia', serif",
    headingFont: "'Georgia', serif",
    fontSize: { name: 26, heading: 15, subheading: 12, body: 11, small: 10 },
    spacing: { sectionGap: 14, itemGap: 8, lineHeight: 1.5 },
    colors: {
      primary: "#78350f",
      secondary: "#57534e",
      accent: "#b45309",
      text: "#292524",
      background: "#ffffff",
      heading: "#78350f",
      border: "#d6d3d1",
    },
    layout: {
      columns: 2,
      sidebarPosition: "right",
      sidebarSections: ["skills", "certifications", "education"],
      mainSections: ["summary", "experience", "projects", "custom"],
    },
    sectionOrder: ["header", "summary", "experience", "projects", "skills", "education", "certifications", "custom"],
    sectionVisibility: {
      header: true, summary: true, experience: true, projects: true,
      skills: true, education: true, certifications: true, custom: true,
    },
  },
]

export function getTemplate(id: string): TemplateConfig {
  return templates.find((t) => t.id === id) || templates[0]
}

export const roleSkillMap: Record<string, string[]> = {
  "Full Stack Developer": [
    "JavaScript", "TypeScript", "React", "Next.js", "Node.js", "Express.js",
    "PostgreSQL", "MongoDB", "REST APIs", "GraphQL", "Git", "Docker",
    "AWS", "CI/CD", "HTML", "CSS", "Tailwind CSS", "Redis", "Testing", "Agile",
  ],
  "Backend Developer": [
    "Node.js", "Python", "Java", "Go", "PostgreSQL", "MySQL", "MongoDB",
    "Redis", "REST APIs", "GraphQL", "Docker", "Kubernetes", "AWS",
    "Microservices", "Message Queues", "CI/CD", "Git", "Linux", "Testing", "System Design",
  ],
  "Frontend Developer": [
    "JavaScript", "TypeScript", "React", "Next.js", "Vue.js", "Angular",
    "HTML", "CSS", "Tailwind CSS", "SASS", "Webpack", "Vite",
    "Testing", "Accessibility", "Performance", "Responsive Design", "Git", "Figma", "REST APIs", "State Management",
  ],
  "AI / Data Engineer": [
    "Python", "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy",
    "SQL", "Spark", "Hadoop", "Machine Learning", "Deep Learning", "NLP",
    "Computer Vision", "Data Pipelines", "AWS", "Docker", "Git", "Statistics", "MLOps", "Jupyter",
  ],
  "DevOps Engineer": [
    "Docker", "Kubernetes", "AWS", "GCP", "Azure", "Terraform",
    "CI/CD", "Jenkins", "GitHub Actions", "Linux", "Bash", "Python",
    "Monitoring", "Prometheus", "Grafana", "Networking", "Security", "Git", "Ansible", "Helm",
  ],
  "Mobile Developer": [
    "React Native", "Flutter", "Swift", "Kotlin", "iOS", "Android",
    "JavaScript", "TypeScript", "REST APIs", "GraphQL", "Firebase",
    "Git", "App Store", "Play Store", "UI/UX", "Testing", "CI/CD", "Push Notifications", "State Management", "Offline Storage",
  ],
  "Data Analyst": [
    "SQL", "Python", "R", "Excel", "Tableau", "PowerBI", "Data Visualization",
    "Statistics", "Data Cleaning", "SAS", "Google Analytics", "Looker", "Jupyter", "Git",
  ],
  "Data Scientist": [
    "Python", "R", "SQL", "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch",
    "Scikit-learn", "Pandas", "NumPy", "Statistics", "Big Data", "Hadoop", "Spark",
    "Data Mining", "Data Visualization", "Jupyter", "Git", "A/B Testing",
  ],
}

export const defaultResumeData = {
  personal: {
    fullName: "",
    email: "",
    phone: "",
    location: "",
    linkedin: "",
    github: "",
    portfolio: "",
    title: "",
    photoUrl: "",
  },
  summary: "",
  skills: [],
  experience: [],
  projects: [],
  education: [],
  certifications: [],
  customSections: [],
}