-- More fresher-friendly jobs from various companies and sources
INSERT INTO jobs (title, company, location, job_type, experience_level, description, skills, salary_range, apply_url, source, posted_at) VALUES
-- Indian IT & Startups
('Graduate Engineer Trainee', 'Infosys', 'Mysore, India', 'Full-time', 'Fresher', 'Join Infosys as a Graduate Engineer Trainee and receive world-class training at the Mysore campus.', ARRAY['Java', 'SQL', 'Problem Solving', 'Communication'], '$8K-$12K/yr', 'https://career.infosys.com', 'Infosys Careers', NOW() - INTERVAL '1 day'),
('Systems Engineer', 'TCS', 'Chennai, India', 'Full-time', 'Fresher', 'TCS hiring freshers as Systems Engineers for enterprise projects.', ARRAY['Java', 'Python', 'SQL', 'Linux'], '$7K-$11K/yr', 'https://ibegin.tcs.com', 'TCS iBegin', NOW() - INTERVAL '2 days'),
('Project Engineer', 'Wipro', 'Bangalore, India', 'Full-time', 'Fresher', 'Wipro hiring fresh graduates for WILP and NTH programs.', ARRAY['Java', 'C++', 'Databases', 'Agile'], '$7K-$10K/yr', 'https://careers.wipro.com', 'Wipro Careers', NOW() - INTERVAL '2 days'),
('Associate Software Engineer', 'Accenture', 'Hyderabad, India', 'Full-time', 'Fresher', 'Build innovative solutions at Accenture with mentoring and rapid career growth.', ARRAY['JavaScript', 'Java', 'Cloud', 'Agile'], '$9K-$14K/yr', 'https://accenture.com/careers', 'Accenture Careers', NOW() - INTERVAL '3 days'),
('Software Developer Intern', 'Razorpay', 'Bangalore, India', 'Internship', 'Fresher', 'Work on fintech infrastructure serving millions of businesses.', ARRAY['Go', 'JavaScript', 'MySQL', 'AWS'], '$800-$1.5K/mo', 'https://razorpay.com/jobs', 'Razorpay Careers', NOW() - INTERVAL '1 day'),
('Frontend Engineer - New Grad', 'Flipkart', 'Bangalore, India', 'Full-time', 'Entry Level', 'Join India''s leading e-commerce platform to build next-gen shopping experiences.', ARRAY['React', 'TypeScript', 'CSS', 'Node.js'], '$15K-$22K/yr', 'https://flipkart.com/careers', 'Flipkart Careers', NOW() - INTERVAL '4 days'),
('SDE-1 New Graduate', 'PhonePe', 'Bangalore, India', 'Full-time', 'Entry Level', 'Build India''s leading digital payments platform at massive scale.', ARRAY['Java', 'Spring Boot', 'Kafka', 'PostgreSQL'], '$18K-$25K/yr', 'https://phonepe.com/careers', 'PhonePe Careers', NOW() - INTERVAL '2 days'),
('Junior Data Analyst', 'Swiggy', 'Bangalore, India', 'Full-time', 'Entry Level', 'Analyze food delivery data to optimize logistics and customer experience.', ARRAY['Python', 'SQL', 'Tableau', 'Statistics'], '$12K-$18K/yr', 'https://careers.swiggy.com', 'Swiggy Careers', NOW() - INTERVAL '5 days'),
('Backend Developer Intern', 'Zerodha', 'Bangalore, India', 'Internship', 'Fresher', 'Work on India''s largest stock brokerage platform.', ARRAY['Go', 'Python', 'PostgreSQL', 'Redis'], '$1K-$2K/mo', 'https://zerodha.com/careers', 'Zerodha Careers', NOW() - INTERVAL '3 days'),
('Associate ML Engineer', 'Ola', 'Bangalore, India', 'Full-time', 'Entry Level', 'Apply machine learning to transform mobility and EV at scale.', ARRAY['Python', 'PyTorch', 'Spark', 'AWS'], '$16K-$24K/yr', 'https://ola.com/careers', 'Ola Careers', NOW() - INTERVAL '4 days'),

-- Global Big Tech
('New Grad SWE - L3', 'Google', 'Mountain View, CA', 'Full-time', 'Entry Level', 'Build products that impact billions. Google''s new grad program.', ARRAY['Java', 'C++', 'Python', 'Algorithms', 'Distributed Systems'], '$120K-$160K/yr', 'https://careers.google.com', 'Google Careers', NOW() - INTERVAL '3 days'),
('Software Engineer Intern', 'Apple', 'Cupertino, CA', 'Internship', 'Fresher', 'Contribute to iPhone, Mac, and services software during a 12-week internship.', ARRAY['Swift', 'Objective-C', 'C++', 'iOS'], '$9K-$12K/mo', 'https://jobs.apple.com', 'Apple Careers', NOW() - INTERVAL '2 days'),
('Junior Backend Engineer', 'Spotify', 'Stockholm, Sweden', 'Full-time', 'Entry Level', 'Help personalize music for 500M+ users worldwide.', ARRAY['Java', 'Python', 'GCP', 'Microservices'], 'EUR 45K-60K/yr', 'https://lifeatspotify.com', 'Spotify Careers', NOW() - INTERVAL '5 days'),
('New Grad Frontend Engineer', 'Airbnb', 'San Francisco, CA', 'Full-time', 'Entry Level', 'Create world-class travel experiences on Airbnb.com.', ARRAY['React', 'TypeScript', 'GraphQL', 'CSS'], '$130K-$165K/yr', 'https://careers.airbnb.com', 'Airbnb Careers', NOW() - INTERVAL '6 days'),
('Associate Cloud Engineer', 'AWS', 'Seattle, WA', 'Full-time', 'Entry Level', 'Help customers build on AWS cloud infrastructure.', ARRAY['AWS', 'Linux', 'Python', 'Terraform', 'Networking'], '$95K-$130K/yr', 'https://amazon.jobs', 'Amazon Jobs', NOW() - INTERVAL '4 days'),
('Junior DevOps Engineer', 'Cloudflare', 'Austin, TX', 'Full-time', 'Entry Level', 'Help build a better internet. Focus on reliability and performance.', ARRAY['Linux', 'Docker', 'Kubernetes', 'Go', 'CI/CD'], '$100K-$135K/yr', 'https://cloudflare.com/careers', 'Cloudflare Careers', NOW() - INTERVAL '3 days'),
('Graduate Data Scientist', 'DeepMind', 'London, UK', 'Full-time', 'Entry Level', 'Advance AI research with one of the world''s top labs.', ARRAY['Python', 'PyTorch', 'TensorFlow', 'Statistics', 'ML'], 'GBP 50K-70K/yr', 'https://deepmind.google/careers', 'DeepMind Careers', NOW() - INTERVAL '7 days'),
('Junior iOS Developer', 'Uber', 'San Francisco, CA', 'Full-time', 'Entry Level', 'Build the Uber rider and driver apps used by millions.', ARRAY['Swift', 'UIKit', 'RxSwift', 'CI/CD'], '$110K-$145K/yr', 'https://uber.com/careers', 'Uber Careers', NOW() - INTERVAL '5 days'),

-- Remote / Global Startups
('Junior Full Stack Developer', 'Supabase', 'Remote', 'Full-time', 'Entry Level', 'Build the open-source Firebase alternative. Fully remote.', ARRAY['TypeScript', 'PostgreSQL', 'React', 'Elixir'], '$80K-$120K/yr', 'https://supabase.com/careers', 'Supabase Careers', NOW() - INTERVAL '2 days'),
('New Grad Software Engineer', 'Linear', 'Remote', 'Full-time', 'Entry Level', 'Build the best issue tracker for modern software teams.', ARRAY['TypeScript', 'React', 'Node.js', 'PostgreSQL'], '$100K-$140K/yr', 'https://linear.app/careers', 'Linear Careers', NOW() - INTERVAL '3 days'),
('Junior Developer Advocate', 'Vercel', 'Remote', 'Full-time', 'Entry Level', 'Teach the world to build with Next.js and the Vercel platform.', ARRAY['Next.js', 'React', 'TypeScript', 'Technical Writing'], '$90K-$125K/yr', 'https://vercel.com/careers', 'Vercel Careers', NOW() - INTERVAL '1 day'),
('Associate Security Engineer', 'CrowdStrike', 'Remote', 'Full-time', 'Entry Level', 'Protect enterprises from cyber threats with AI-powered security.', ARRAY['Python', 'Go', 'Linux', 'AWS', 'Security'], '$85K-$115K/yr', 'https://crowdstrike.com/careers', 'CrowdStrike Careers', NOW() - INTERVAL '4 days'),
('Junior QA Engineer', 'Canva', 'Sydney, Australia', 'Full-time', 'Entry Level', 'Ensure quality for 150M+ users on the visual design platform.', ARRAY['Selenium', 'Python', 'JavaScript', 'CI/CD', 'Testing'], 'AUD 70K-90K/yr', 'https://canva.com/careers', 'Canva Careers', NOW() - INTERVAL '6 days'),
('Graduate Platform Engineer', 'Atlassian', 'Sydney, Australia', 'Full-time', 'Entry Level', 'Work on Jira, Confluence, and Trello backend infrastructure.', ARRAY['Java', 'Kotlin', 'AWS', 'Microservices', 'Docker'], 'AUD 80K-100K/yr', 'https://atlassian.com/careers', 'Atlassian Careers', NOW() - INTERVAL '5 days'),

-- European Tech
('Junior React Developer', 'Klarna', 'Berlin, Germany', 'Full-time', 'Entry Level', 'Build smooth payment experiences for Europe''s fintech leader.', ARRAY['React', 'TypeScript', 'Node.js', 'GraphQL'], 'EUR 50K-65K/yr', 'https://klarna.com/careers', 'Klarna Careers', NOW() - INTERVAL '4 days'),
('Graduate Software Engineer', 'Revolut', 'London, UK', 'Full-time', 'Entry Level', 'Join Europe''s most valuable fintech startup.', ARRAY['Java', 'Kotlin', 'Spring', 'PostgreSQL'], 'GBP 45K-60K/yr', 'https://revolut.com/careers', 'Revolut Careers', NOW() - INTERVAL '3 days'),
('Junior Backend Engineer', 'N26', 'Berlin, Germany', 'Full-time', 'Entry Level', 'Build the bank the world loves to use.', ARRAY['Kotlin', 'Java', 'AWS', 'Microservices'], 'EUR 48K-62K/yr', 'https://n26.com/careers', 'N26 Careers', NOW() - INTERVAL '6 days'),

-- Freelance / Contract
('Junior WordPress Developer', 'Toptal', 'Remote', 'Contract', 'Entry Level', 'Freelance WordPress development through Toptal''s elite network.', ARRAY['WordPress', 'PHP', 'JavaScript', 'CSS', 'MySQL'], '$30-$60/hr', 'https://toptal.com/careers', 'Toptal', NOW() - INTERVAL '2 days'),
('Contract React Native Developer', 'Upwork', 'Remote', 'Contract', 'Entry Level', 'Build mobile apps for clients on the world''s largest freelance platform.', ARRAY['React Native', 'TypeScript', 'Firebase', 'REST APIs'], '$25-$50/hr', 'https://upwork.com', 'Upwork', NOW() - INTERVAL '1 day');
